# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4698e2f3a2c37f63418fafff8dc1c0a529e46ed9d921eda10947b076691c58708209fd5562d175d9152c5bba48b7f5070207ce1e1352e9b007bbd6494b3ae8a5

test:
  secret_key_base: 512859a6c518b6615646745dc80cb572b5f4d05c5e525f91fcc74df833f4059cfc77322b42e4f3fd26d6d81bb1be527ed7f09702a18ddbddd3f10f50179ee0f4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
